/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckIn {
  'id' : bigint,
  'wasClean' : boolean,
  'date' : string,
  'note' : string,
}
export interface JournalEntry {
  'id' : bigint,
  'content' : string,
  'date' : string,
  'timestamp' : bigint,
}
export interface Milestone {
  'id' : string,
  'milestoneLabel' : string,
  'earned' : boolean,
  'daysRequired' : bigint,
}
export interface Stats {
  'journalCount' : bigint,
  'totalDaysClean' : bigint,
  'longestStreak' : bigint,
  'urgeCount' : bigint,
  'currentStreak' : bigint,
}
export interface UrgeLog {
  'id' : bigint,
  'note' : string,
  'timestamp' : bigint,
  'intensity' : bigint,
  'triggers' : Array<string>,
}
export interface UserProfile {
  'lastCheckInDate' : [] | [string],
  'longestStreak' : bigint,
  'recoveryStartDate' : [] | [bigint],
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getMilestones' : ActorMethod<[], Array<Milestone>>,
  'getProfile' : ActorMethod<
    [],
    {
      'lastCheckInDate' : [] | [string],
      'longestStreak' : bigint,
      'recoveryStartDate' : [] | [bigint],
      'currentStreak' : bigint,
    }
  >,
  'getStats' : ActorMethod<[], Stats>,
  'getUrgeLogs' : ActorMethod<[], Array<UrgeLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logUrge' : ActorMethod<[bigint, Array<string>, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRecoveryStartDate' : ActorMethod<[string], undefined>,
  'submitCheckIn' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];