/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'lastCheckInDate' : IDL.Opt(IDL.Text),
  'longestStreak' : IDL.Nat,
  'recoveryStartDate' : IDL.Opt(IDL.Int),
  'currentStreak' : IDL.Nat,
});
export const CheckIn = IDL.Record({
  'id' : IDL.Nat,
  'wasClean' : IDL.Bool,
  'date' : IDL.Text,
  'note' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Milestone = IDL.Record({
  'id' : IDL.Text,
  'milestoneLabel' : IDL.Text,
  'earned' : IDL.Bool,
  'daysRequired' : IDL.Nat,
});
export const Stats = IDL.Record({
  'journalCount' : IDL.Nat,
  'totalDaysClean' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'urgeCount' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const UrgeLog = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'intensity' : IDL.Nat,
  'triggers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
  'getProfile' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastCheckInDate' : IDL.Opt(IDL.Text),
          'longestStreak' : IDL.Nat,
          'recoveryStartDate' : IDL.Opt(IDL.Int),
          'currentStreak' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUrgeLogs' : IDL.Func([], [IDL.Vec(UrgeLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logUrge' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text), IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRecoveryStartDate' : IDL.Func([IDL.Text], [], []),
  'submitCheckIn' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'lastCheckInDate' : IDL.Opt(IDL.Text),
    'longestStreak' : IDL.Nat,
    'recoveryStartDate' : IDL.Opt(IDL.Int),
    'currentStreak' : IDL.Nat,
  });
  const CheckIn = IDL.Record({
    'id' : IDL.Nat,
    'wasClean' : IDL.Bool,
    'date' : IDL.Text,
    'note' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Text,
    'milestoneLabel' : IDL.Text,
    'earned' : IDL.Bool,
    'daysRequired' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'journalCount' : IDL.Nat,
    'totalDaysClean' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'urgeCount' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const UrgeLog = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'intensity' : IDL.Nat,
    'triggers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getMilestones' : IDL.Func([], [IDL.Vec(Milestone)], ['query']),
    'getProfile' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastCheckInDate' : IDL.Opt(IDL.Text),
            'longestStreak' : IDL.Nat,
            'recoveryStartDate' : IDL.Opt(IDL.Int),
            'currentStreak' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUrgeLogs' : IDL.Func([], [IDL.Vec(UrgeLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logUrge' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text), IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRecoveryStartDate' : IDL.Func([IDL.Text], [], []),
    'submitCheckIn' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };